import type { HumidorItem } from "@/lib/live-api";

export const demoHumidorItems: HumidorItem[] = [
  {
    id: "demo-padron-1964-anniversary",
    name: "1964 Anniversary Series",
    brand: "Padron",
    line: "Anniversary",
    vitola: "Torpedo",
    wrapper: "Natural",
    origin: "Nicaragua",
    strength: "Full",
    quantity: 8,
    rating: 94,
    purchaseDate: "2025-01-18",
    agingStartDate: "2025-02-01",
    productionDate: "2023-11-01",
    reorderReminder: "2026-06-15",
    humidorLocation: "Locker A",
    tray: "Drawer 2",
    tastingNotes: "Cocoa, cedar, and toasted almond with a long finish.",
    source: "demo_humidor",
    estimatedValue: 32,
    estimatedValueCurrency: "USD",
    estimatedValueSource: "demo_entry_price_snapshot",
    cigarImage: {
      imageUrl: "/assets/product-padron.png",
      mimeType: "image/png",
      fileName: "product-padron.png",
      bytes: 56412,
      source: "demo_humidor",
    },
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "demo-davidoff-signature-no-2",
    name: "Signature No. 2",
    brand: "Davidoff",
    line: "Signature",
    vitola: "Panetela",
    wrapper: "Connecticut",
    origin: "Dominican Republic",
    strength: "Mild-Medium",
    quantity: 12,
    rating: 90,
    purchaseDate: "2025-07-05",
    agingStartDate: "2025-07-20",
    productionDate: "2024-02-15",
    reorderReminder: null,
    humidorLocation: "Home Humidor",
    tray: "Top Tray",
    tastingNotes: "Creamy cedar, roasted almond, and clean white pepper.",
    source: "demo_humidor",
    estimatedValue: 24,
    estimatedValueCurrency: "USD",
    estimatedValueSource: "demo_entry_price_snapshot",
    cigarImage: {
      imageUrl: "/assets/product-davidoff.png",
      mimeType: "image/png",
      fileName: "product-davidoff.png",
      bytes: 60919,
      source: "demo_humidor",
    },
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "demo-liga-privada-t52",
    name: "T52",
    brand: "Liga Privada",
    line: "T52",
    vitola: "Toro",
    wrapper: "Habano",
    origin: "Nicaragua",
    strength: "Full",
    quantity: 6,
    rating: 92,
    purchaseDate: "2025-10-10",
    agingStartDate: "2025-10-10",
    productionDate: "2024-09-01",
    reorderReminder: "2026-05-30",
    humidorLocation: "Locker B",
    tray: "Drawer 1",
    tastingNotes: "Earth, black pepper, oak, and a dense molasses finish.",
    source: "demo_humidor",
    estimatedValue: 19.5,
    estimatedValueCurrency: "USD",
    estimatedValueSource: "demo_entry_price_snapshot",
    cigarImage: {
      imageUrl: "/assets/product-liga.png",
      mimeType: "image/png",
      fileName: "product-liga.png",
      bytes: 52326,
      source: "demo_humidor",
    },
    createdAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "demo-plasencia-alma-fuerte",
    name: "Alma Fuerte Sixto I",
    brand: "Plasencia",
    line: "Alma Fuerte",
    vitola: "Hexagono",
    wrapper: "Maduro",
    origin: "Nicaragua",
    strength: "Medium-Full",
    quantity: 5,
    rating: null,
    purchaseDate: "2026-02-14",
    agingStartDate: null,
    productionDate: "2025-08-01",
    reorderReminder: null,
    humidorLocation: "Travel Case",
    tray: "Slot 3",
    tastingNotes: "Resting for a longer tasting note after the next smoke.",
    source: "demo_humidor",
    estimatedValue: 26,
    estimatedValueCurrency: "USD",
    estimatedValueSource: "demo_entry_price_snapshot",
    cigarImage: {
      imageUrl: "/assets/product-plasencia.png",
      mimeType: "image/png",
      fileName: "product-plasencia.png",
      bytes: 54099,
      source: "demo_humidor",
    },
    createdAt: "2026-05-01T00:00:00.000Z",
  },
];
